routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['auth']], function () {
    
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users','UsersController')->except(['store','create']); 
Route::resource('comment', 'CommentController');
Route::resource('follow', 'FollowController');

/*-- tambahan --*/

Route::get('/dashboard',[
    'uses'=> 'FeedController@getDashboard',
    'as'=>'dashboard'
])->middleware('auth');

Route::post('/createpost', [
    'uses' => 'FeedController@postCreatePost',
    'as' => 'post.create'
])->middleware('auth');


Route::get('/delete-post/{post_id}', [
    'uses' => 'FeedController@getDeletePost',
    'as' => 'post.delete'
])->middleware('auth');


Route::post('/like', [
    'uses' => 'FeedController@postLikePost',
    'as' => 'like'
]);

Route::post('/edit', [
    'uses' => 'FeedController@postEditPost',
    'as' => 'edit'
]);

Route::get('/show/{user_id}', [
    'uses' => 'FeedController@getUserPost',
    'as' => 'show'
])->middleware('auth');
/*--end tambahan --*/
});

Route::get('/', function () {
    return view('login');
});

Auth::routes(['verify'=>true]);

resources/views/layout/partial/header.blade.php
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <a href="/dashboard" class="navbar-brand"><b>Sosmed</b>LTE</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
              <i class="fa fa-bars"></i>
            </button>
          </div>

         
          <!-- Navbar Right Menu -->

            <div class="navbar-custom-menu">
              <ul class="nav navbar-nav">
                
                <!-- User Account Menu -->
                <li class="nav-item dropdown">
                  <!-- Menu Toggle Button -->
                  <a href="#" id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                    <span class="hidden-xs">{{Auth::user()->name}}</span>
                  </a>
                  
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                 </div>
                
                </li>
              </ul>
            </div><!-- /.navbar-custom-menu -->
            
        </div><!-- /.container-fluid -->
      </nav>
  </header>

resources/views/layout/partial/modal.blade.php
<div class="modal fade" id="addComment" style="display: none;" methot="post" action="{{action('CommentController@store')}}" role="form">
  @csrf
  <div class="modal-dialog" >
    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Comment</h4>
      </div>
      <div class="modal-body">
        <form role="form" enctype="multipart/form-data" action="{{ route('comment.store') }}" method="POST">
          @csrf
        <div class="box-body">
          <div class="form-group">
            @foreach($posts as $post)
            <input type="hidden" value="{{$post->id}}" name="feed">
            <input type="hidden" value="{{$post->users_id}}" name="user">
            @endforeach
            <textarea class="form-control" id="comment" rows="6" cols="30" placeholder="Whats Happening?" name="comment"> </textarea>
          </div>
        </div><!-- /.box-body -->
  
        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

resources/views/layout/partial/sidebar.blade.php
<div class="col-md-4">
        <!--<div class="row"> -->
            <div class="box box-primary">
                <div class="box-header with-border">
                  @if (is_null(Auth::user()->photo))
                      <img class="img-circle " src="{{asset('img/default_ava.png')}}" alt="User Image" style="display: block; margin-left: auto; margin-right: auto;" width="150" height="200">
                  @else
                      <img class="img-circle " src="{{asset('uploads/avatar/'.Auth::user()->photo )}}" alt="User Image" style="display: block; margin-left: auto; margin-right: auto;" width="150" height="200">
                  @endif

                    <p style="text-align: center;">
                      {{Auth::user()->name}}
                      <a href="/users/{{Auth::user()->id}}/edit" class="fa fa-edit"></a>
                    </p>
                    
                </div>
                  <!-- Menu Body -->
                
                  <div class="box-body">
                      <div class="text-center d-flex justify-content-md-between">
                        <a href="#" class="btn btn-primary">{{$count_followers}} Followers</a>
                        <a href="{{route('show', ['user_id' => Auth::user()->id])}}" class="btn btn-primary">{{$count_feeds}} Feeds</a>
                        <a href="#" class="btn btn-primary">{{$count_following}} Following</a>
                      </div>
                      
                  </div>
                    <!-- Menu Footer-->
            </div><!-- /.box -->
            <div class="box box-primary">
            
                    <div class="box-header with-border">
                        
                        <h2>
                          Suggestion
                        </h2>
                    </div>
                      <!-- Menu Body -->
                    <div class="box-body" id="suggestion" >
                        
                              @foreach($suggestion as $item)
                                <div class="media">
                                    @if (is_null($item->photo))
                                      <img src="{{asset('img/default_ava.png')}}" class="card-img-top" alt="Generic placeholder image" style="width:50px;height:50px;">
                                    @else
                                      <img src="{{asset('uploads/avatar/'.$item->photo)}}" class="card-img-top" alt="Generic placeholder image" style="width:50px;height:50px;">
                                    @endif
                                    
                                    <div class="media-body">
                                      
                                      <form method="POST" enctype="multipart/form-data" action="/follow">
                                        @csrf
                                        <h5 class="mt-0" value="{{ $item->name }}">{{ $item->name }}</h5>
                                        <input type="hidden" name="follow" value="{{ $item->id }}">
                                        @error('follow')
                                            <div class="alert alert-danger">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                        <input type="hidden" name="name" value="{{ $item->name }}">
                                        @error('name')
                                            <div class="alert alert-danger">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                        <button type="submit" class="btn btn-primary">Follow</button>
                                      </form>
                                    </div>
                                </div>
                              @endforeach
                    

                    </div><!-- Menu Footer-->
                </div><!-- /.box -->
    
      </div>
     



    


      